### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by lerucom** [lerucom/js-homework1#1]
@coursar
Развертывание GitHub Pages [https://lerucom.github.io/js-homework/](https://lerucom.github.io/js-homework/)
1. Задание [кофемат](https://github.com/lerucom/js-homework/blob/master/src/js/cofemat.js)
2. Задание [расстояние](https://github.com/lerucom/js-homework/blob/master/src/js/roadTrip.js)
3. Задание [обои](https://github.com/lerucom/js-homework/blob/master/src/js/wallpaper.js)
4. Задание [знак зодиака](https://github.com/lerucom/js-homework/blob/master/src/js/zodiacSigns.js)

**Comment by coursar** [comment]
На один проект - один репозиторий. Соответственно, и сайты должны быть разные

**Comment by lerucom** [comment]
@coursar 
* Исправлено:
  * Развертывание GitHub Pages https://lerucom.github.io/js-homework/
  * Оставил один проект cofemat
  * В папке \src\js теперь lib.js, app.js
  * Дополнил index.html - добавил input, button, label
* Не работает:
  * Кнопка **[Купить](https://lerucom.github.io/js-homework/)** - не работает, не понимаю, что не так?
![cofemat-error](https://user-images.githubusercontent.com/36261294/50963898-02474b00-14df-11e9-81b7-250875aac74d.jpg)

**Comment by coursar** [comment]
Отлично, тогда переименуйте текущий в настройках

**Comment by lerucom** [comment]
@coursar 
@sergcen 
*  Переименовал с **js-homework** в **js-homework1** (по аналогии с другими домашками js-homework2, ... )
*  Вопрос: на codecov & travis ci у репозитория старое название **js-homework**, и локально на пк. Что делать? 
* codecov после переименования репозитория выдает ошибку: Unable to find commit in GitHub
* travis ci после переименования репозитория выдает ошибку: 

> gh-token is invalid. Details: GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3
> Preparing deploy
> failed to deploy

**Comment by lerucom** [comment]
@coursar
*  Готово! Решение - обновил GITHUB_TOKEN.
